### PR TITLE
Placeholder flash and second SPI

### PR DESCRIPTION
**Pull request by HenryFree3**
From the M3 flight data:
Data rate estimate is ~32 KB/s each for dart and booster. From CamPyRoS, M4 flight time is just under 400 seconds, so 512 Mbit works for a factor of >2 with a data rate of 64 KB/s (410 Mbit)
- Logging to the flash would need to start at / just before ignition - for M3 there's 45 minutes of pad data

The Winbond W25Q80 is added to the schematic as a placeholder, as it's the only SPI flash currently in the CUSF library. Winbond make a 512 Mbit chip which is a 16 pin package, the W25M512JV, and there are [libraries ](https://github.com/dberenguer/SPIFlash)/ usage examples of the W25 chips with STM32s.

### CODE REVIEW

**Comment by henryefranks** [comment]
Are there any other chips with larger capacity that we could use? Adding the chip into the kicad lib won't be difficult so we shouldn't arbitrarily limit ourselves to what's already there. Getting some pad data would probably be good for review after, and constricting ourselves to begin logging at launch does worry me a bit if anything because of the small margin or error there. Implementing SPI data storage doesn't strike me as too difficult from the software side of things so swapping it out for a different SPI flash chip shouldn't be a problem. I'll take a look over the schematic later but that's just a couple thoughts I had from what you've said.

**Comment by HenryFree3** [comment]
NOR chips are available up to 2 Gbit:

- Seems like 512 Mbit are the largest single die, dual die would be fine; I only stuck with the 512 Mbit single die chip as I had seen two chip selects on a datasheet for a dual die chip and thought I'd stick with the simplest option, although it looks like you can get dual dies where that's handled by the chip itself and there's only 1 CS still
- The 2 Gbit chips are only available in BGA packages, also multi die

NAND flash is available as 2 Gbit, single die, SMT mounted, but slower than NOR. I would be surprised if speed was a problem though, so probably the best option overall.

**Comment by HenryFree3** [comment]
I was mistaken about the speeds - NOR has faster access times because the bits can be read independently but NAND writes faster.

**Comment by henryefranks** [comment]
Just had a look through the schematics, and it looks like kicad's done it's usual and committed a whole rescue copy of every symbol we're using. Any chance you could make sure you've done `git submodule update --init` and delete that rescue lib both as a file and from the sym-lib-table? I know it's a real pain but kicad's super finnicky sometimes and I've found it's often better to fix these things early before they cause a problem further down the line.

Other than that, it looks great! I think once you get that rescue lib cleaned up we should be good to merge this. I think we could leave a review of the flash chip for a little further down the road once everything else is sorted, as it sounds like what we've got at the moment will work, and given it's SPI we could easily swap it out for a different one where required. Thanks for all your hard work on this.

**Comment by HenryFree3** [comment]
Probably a result of me cloning the kicad library rather than doing things properly in the first place, hopefully that's now better?

**Comment by henryefranks** [comment]
You might have to remove both `m4-avionics-rescue.lib` and `m4-avionics-rescue.dcm` too.

**Comment by HenryFree3** [comment]
Convinced I deleted them the first time but obviously not...

**Comment by henryefranks** [comment]
No sweat, thanks.

**Pull request merged**
